import streamlit as st
import joblib
import re
import string

# Load model and vectorizer

model = joblib.load("model.pkl")
vectorization = joblib.load("vectorization.pkl")

# Text preprocessing

def wordopt(text):
    text = text.lower()
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub(r'\w*\d\w*', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text



# Page title
st.title("📰 VERINEWS - Verify Your News")

st.write(
"Paste a news article below and click Predict to classify whether the news is likely Fake or Real."
)

# Input box

news = st.text_area(
"Enter News Article",
height=250
)

# Prediction button

if st.button("Predict"):
    cleaned_news = wordopt(news)

    transformed_news = vectorization.transform([cleaned_news])

    prediction = model.predict(transformed_news)

    probability = model.predict_proba(transformed_news)
    confidence = probability.max() * 100

    
    if prediction[0] == 0:
        st.error("🚨 Fake News")
    else:
        st.success("✅ Real News")
    st.write(f"Confidence Score: {confidence:.2f}%")

# Disclaimer

st.markdown("---")

st.caption(
"⚠️ This prediction is generated by a Machine Learning model and may not always be correct. "
"Please verify important information using trusted news sources."
)

st.caption("Developed using Logistic Regression, TF-IDF and Streamlit.")

